name: Python Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Python dependencies
      run: |
            python -m pip install marshmallow 
            python -m pip install typeguard
            python -m pip install pytest # if necessary
    - name: Run tests
      run: |
          pytest S19/test_smart_device.py
          

